# Generated by Django 3.2.7 on 2021-09-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_chatbot', '0005_auto_20210502_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='method',
            field=models.CharField(choices=[('myapp.responses.GreetingResponse', 'Greeting'), ('myapp.responses.GoodbyeResponse', 'Goodbye'), ('myapp.responses.ProductInformationResponse', 'Information')], max_length=120, unique=True, verbose_name='Method'),
        ),
    ]
