# Generated by Django 3.2.7 on 2021-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_chatbot', '0006_alter_tag_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='method',
            field=models.CharField(choices=[('myapp.responses.GreetingResponse', 'Greeting'), ('myapp.responses.GoodbyeResponse', 'Goodbye'), ('myapp.responses.ProductInformationResponse', 'Information'), ('myapp.responses.UnableToAnswer', 'Unable')], max_length=120, unique=True, verbose_name='Method'),
        ),
    ]
